In [3]:
import numpy as np

In [13]:
batch_size = 8
in_feature = 2
out_feature = 3

x = np.random.random((batch_size,in_feature))
W = np.random.random((in_feature, out_feature))
b = np.random.random((1,out_feature))
print(W)
print(W.sum(axis=0))

[[0.14747204 0.66815595 0.70853712]
 [0.65021236 0.20659561 0.18273222]]
[0.79768439 0.87475155 0.89126934]


In [16]:

a.sum()?

SyntaxError: invalid syntax (<ipython-input-16-36c6c9f901dd>, line 2)

In [66]:
print(a)
a.mean(axis=1)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37.
  38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54. 55. 56. 57.
  58. 59.]]


array([ 9.5, 29.5, 49.5])

In [69]:
a = [1,2] + 4
a.shape[1]

TypeError: can only concatenate list (not "int") to list

In [32]:
np.stack?

In [45]:
a
a.reshape((1,2))


array([[5, 6]])

In [76]:
alpha = 0.9
eps = 1e-8
x = None
norm = None
out = None
in_feature = 15

# The following attributes will be tested
var = np.ones((1, in_feature))
mean = np.zeros((1, in_feature))

gamma = np.ones((1, in_feature))
dgamma = np.zeros((1, in_feature))

beta = np.zeros((1, in_feature))
dbeta = np.zeros((1, in_feature))

# inference parameters
running_mean = np.zeros((1, in_feature))
running_var = np.ones((1, in_feature))

In [113]:
np.sqrt?

In [108]:
x =np.arange(150.0).reshape((10, 15))

In [112]:
print("x shape", x.shape,x)
mean = x.mean(axis=0)
print(running_mean.shape)
print(mean)
var = np.var(x,axis=0)
print("var",var)
#print(np.subtract(x,mean).shape)
norm = ((x - mean)/(np.sqrt(np.power(mean,2) + eps)))
out = gamma * norm + beta
# Update running batch statistics
running_mean = alpha * running_mean+ (1-alpha) * mean
running_var = alpha * var + (1-alpha) * var

print(out)

x shape (10, 15) [[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
   14.]
 [ 15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
   29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.
   44.]
 [ 45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.
   59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.  72.  73.
   74.]
 [ 75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.
   89.]
 [ 90.  91.  92.  93.  94.  95.  96.  97.  98.  99. 100. 101. 102. 103.
  104.]
 [105. 106. 107. 108. 109. 110. 111. 112. 113. 114. 115. 116. 117. 118.
  119.]
 [120. 121. 122. 123. 124. 125. 126. 127. 128. 129. 130. 131. 132. 133.
  134.]
 [135. 136. 137. 138. 139. 140. 141. 142. 143. 144. 145. 146. 147. 148.
  149.]]
(1, 15)
[67.5 68.5 69.5 70.5 71.5 72.5 73.5 74.5 75.5 76.5 77.5 78.5 79.5 80.5
 81.5]
var [1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25 1856.25
 1856.25 1856.25 18

In [1]:

sys.path.append('mytorch')
from loss import *
from activation import *
from batchnorm import *
from linear import *


NameError: name 'sys' is not defined

In [2]:
# Do not import any additional 3rd party external libraries as they will not
# be available to AutoLab and are not needed (or allowed)

import numpy as np
import math

class Linear():
    def __init__(self, in_feature, out_feature, weight_init_fn, bias_init_fn):

        """
        Argument:
            W (np.array): (in feature, out feature)
            dW (np.array): (in feature, out feature)
            momentum_W (np.array): (in feature, out feature)

            b (np.array): (1, out feature)
            db (np.array): (1, out feature)
            momentum_B (np.array): (1, out feature)
        """

        self.W = weight_init_fn(in_feature, out_feature)
        self.b = bias_init_fn(out_feature)

        # TODO: Complete these but do not change the names.
        self.dW = np.zeros(None)
        self.db = np.zeros(None)
        
        self.in_feature = 0
        self.x = np.zeros(None)

        self.momentum_W = np.zeros(None)
        self.momentum_b = np.zeros(None)

    def __call__(self, x):
        return self.forward(x)

    def forward(self, x):
        """
        Argument:
            x (np.array): (batch size, in feature)
        Return:
            out (np.array): (batch size, out feature)
        """
        #raise NotImplemented
        self.in_feature = x.shape[0]
        self.x = x
        return x.dot(self.W) + self.b
        

    def backward(self, delta):

        """
        Argument:
            delta (np.array): (batch size, out feature)
        Return:
            out (np.array): (batch size, in feature)
        """
        #raise NotImplemented
        self.dW = 1/ self.in_feature * self.x.T.dot(delta)
        self.db = (1/self.in_feature * delta.sum(axis=0, keepdims=True))
        out = delta.dot(self.W.T)
        return out
        
        


In [3]:
# Do not import any additional 3rd party external libraries as they will not
# be available to AutoLab and are not needed (or allowed)

import numpy as np
import os
#import math


class Activation(object):

    """
    Interface for activation functions (non-linearities).

    In all implementations, the state attribute must contain the result,
    i.e. the output of forward (it will be tested).
    """

    # No additional work is needed for this class, as it acts like an
    # abstract base class for the others

    # Note that these activation functions are scalar operations. I.e, they
    # shouldn't change the shape of the input.

    def __init__(self):
        self.state = None

    def __call__(self, x):
        return self.forward(x)

    def forward(self, x):
        raise NotImplemented

    def derivative(self):
        raise NotImplemented


class Identity(Activation):

    """
    Identity function (already implemented).
    """

    # This class is a gimme as it is already implemented for you as an example

    def __init__(self):
        super(Identity, self).__init__()

    def forward(self, x):
        self.state = x
        return x

    def derivative(self):
        return 1.0


class Sigmoid(Activation):

    """
    Sigmoid non-linearity
    """

    # Remember do not change the function signatures as those are needed
    # to stay the same for AutoLab.

    def __init__(self):
        super(Sigmoid, self).__init__()

    def forward(self, x):
        # Might we need to store something before returning?
        self.state = 1./(1+np.exp(-x))
        return self.state

    def derivative(self):
        # Maybe something we need later in here...
        return self.state * (1-self.state)


class Tanh(Activation):

    """
    Tanh non-linearity
    """

    def __init__(self):
        super(Tanh, self).__init__()

    def forward(self, x):
        self.state = (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
        return self.state

    def derivative(self):
        return 1 - np.power(self.state,2)


class ReLU(Activation):

    """
    ReLU non-linearity
    """

    def __init__(self):
        super(ReLU, self).__init__()

    def forward(self, x):
        self.state = np.where(x>0,x,0)
        return self.state

    def derivative(self):
        return np.where(self.state>0,1.,0)



In [10]:

import numpy as np
import os
import sys

sys.path.append('mytorch')



class MLP(object):

    """
    A simple multilayer perceptron
    """

    def __init__(self, input_size, output_size, hiddens, activations, weight_init_fn,
                 bias_init_fn, criterion, lr, momentum=0.0, num_bn_layers=0):

        # Don't change this -->
        self.train_mode = True
        self.num_bn_layers = num_bn_layers
        self.bn = num_bn_layers > 0
        self.nlayers = len(hiddens) + 1
        self.input_size = input_size
        self.output_size = output_size
        self.activations = activations
        self.criterion = criterion
        self.lr = lr
        self.momentum = momentum
        # <---------------------

        # Don't change the name of the following class attributes,
        # the autograder will check against these attributes. But you will need to change
        # the values in order to initialize them correctly

        # Initialize and add all your linear layers into the list 'self.linear_layers'
        # (HINT: self.foo = [ bar(???) for ?? in ? ])
        # (HINT: Can you use zip here?)
        #Linear: (in_feature, out_feature, weight_init_fn, bias_init_fn)
        activations
        self.linear_layers = [Linear((t[0],t[1],weight_init_fn,bias_init_fn)) for t in zip(np.hstack((self.input_size,hiddens)), np.hstack((hiddens,self.output_size)))]

        # If batch norm, add batch norm layers into the list 'self.bn_layers'
        if self.bn:
            BatchNorm(_in_feature)
            self.bn_layers = self.num_bn_layers#NOT SURE


    def forward(self, x):
        """
        Argument:
            x (np.array): (batch size, input_size)
        Return:
            out (np.array): (batch size, output_size)
        """
        # Complete the forward pass through your entire MLP.
        raise NotImplemented

    def zero_grads(self):
        # Use numpyArray.fill(0.0) to zero out your backpropped derivatives in each
        # of your linear and batchnorm layers.
        raise NotImplemented

    def step(self):
        # Apply a step to the weights and biases of the linear layers.
        # Apply a step to the weights of the batchnorm layers.
        # (You will add momentum later in the assignment to the linear layers only
        # , not the batchnorm layers)

        for i in range(len(self.linear_layers)):
            # Update weights and biases here
            pass
        # Do the same for batchnorm layers

        raise NotImplemented

    def backward(self, labels):
        # Backpropagate through the activation functions, batch norm and
        # linear layers.
        # Be aware of which return derivatives and which are pure backward passes
        # i.e. take in a loss w.r.t it's output.
        raise NotImplemented

    def error(self, labels):
        return (np.argmax(self.output, axis = 1) != np.argmax(labels, axis = 1)).sum()

    def total_loss(self, labels):
        return self.criterion(self.output, labels).sum()

    def __call__(self, x):
        return self.forward(x)

    def train(self):
        self.train_mode = True

    def eval(self):
        self.train_mode = False



In [16]:
def weight(in_feature,out_feature):
    return np.random.randint((in_feature,out_feature))


def bias(out_feature):
    return np.random.randint(out_feature)

MLP(784, 10, [64, 64, 32], [Sigmoid(), Sigmoid(), Sigmoid(), Identity()],
weight, bias, Sigmoid(), 0.008, momentum=0.9, num_bn_layers=0)


t (784, 64) 784 64
t (64, 64) 64 64
t (64, 32) 64 32
t (32, 10) 32 10


In [17]:
# Do not import any additional 3rd party external libraries as they will not
# be available to AutoLab and are not needed (or allowed)

import numpy as np
import os
#import math


class Activation(object):

    """
    Interface for activation functions (non-linearities).

    In all implementations, the state attribute must contain the result,
    i.e. the output of forward (it will be tested).
    """

    # No additional work is needed for this class, as it acts like an
    # abstract base class for the others

    # Note that these activation functions are scalar operations. I.e, they
    # shouldn't change the shape of the input.

    def __init__(self):
        self.state = None

    def __call__(self, x):
        return self.forward(x)

    def forward(self, x):
        raise NotImplemented

    def derivative(self):
        raise NotImplemented


class Identity(Activation):

    """
    Identity function (already implemented).
    """

    # This class is a gimme as it is already implemented for you as an example

    def __init__(self):
        super(Identity, self).__init__()

    def forward(self, x):
        self.state = x
        return x

    def derivative(self):
        return 1.0


class Sigmoid(Activation):

    """
    Sigmoid non-linearity
    """

    # Remember do not change the function signatures as those are needed
    # to stay the same for AutoLab.

    def __init__(self):
        super(Sigmoid, self).__init__()

    def forward(self, x):
        # Might we need to store something before returning?
        self.state = 1./(1+np.exp(-x))
        return self.state

    def derivative(self):
        # Maybe something we need later in here...
        return self.state * (1-self.state)


class Tanh(Activation):

    """
    Tanh non-linearity
    """

    def __init__(self):
        super(Tanh, self).__init__()

    def forward(self, x):
        self.state = (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
        return self.state

    def derivative(self):
        return 1 - np.power(self.state,2)


class ReLU(Activation):

    """
    ReLU non-linearity
    """

    def __init__(self):
        super(ReLU, self).__init__()

    def forward(self, x):
        self.state = np.where(x>0,x,0)
        return self.state

    def derivative(self):
        return np.where(self.state>0,1.,0)



In [26]:
s = Sigmoid()
s.forward(x=3)
s.derivative()

0.045176659730912

In [35]:
u = np.array(1.,2)

TypeError: data type not understood

In [34]:
u.shape

()

In [12]:
a = ([1,2,3],[5,6,7])
a[1]

[5, 6, 7]

In [14]:
import math

In [21]:
def func_z(x,y):
    return 20 + x**2+y**2-10*math.cos(2*math.pi*x)
def der_z(x,y):
    return (2*x + 20 * math.pi * math.sin(2*math.pi*x), 2 * y)

lr = 0.001
steps = 100

In [24]:
(x,y) = (-1.8,-0.2)
for i in range(100):
    print(x,y,func_z(x,y))
    x = x + lr*der_z(x,y)[0]
    y = y + lr*der_z(x,y)[1]
print("res",x,y,func_z(x,y))

-1.8 -0.2 20.189830056250532
-1.743843356705169 -0.20040000000000002 23.467886650627648
-1.6845461952796037 -0.20080080000000003 26.875647868839046
-1.6303224491852346 -0.20120240160000002 29.5291217522063
-1.5876935970887835 -0.20160480640320003 31.081455087392804
-1.557974289046204 -0.20200801601600643 31.811956198092478
-1.5387057028183517 -0.20241203204803845 32.11432120732432
-1.5266528940576183 -0.20281685611213454 32.231908384605184
-1.519233171559981 -0.2032224898243588 32.276439355644726
-1.514697153433756 -0.20362893480400754 32.29316456265041
-1.51193258708334 -0.20403619267361556 32.29947808403062
-1.510250067844981 -0.2044442650589628 32.301921111448095
-1.5092268001725495 -0.2048531535890807 32.302930308305704
-1.5086046991557744 -0.20526285989625886 32.303409462129956
-1.508226564159408 -0.2056733856160514 32.30369310681486
-1.507996745925665 -0.2060847323872835 32.303904939547365
-1.5078570788350898 -0.20649690185205807 32.30409067379792
-1.5077722023901214 -0.206909895

In [26]:
import numpy as np


In [30]:
np.random.shuffle(zip(([1,2,3],[4,5,6])))

TypeError: object of type 'zip' has no len()

In [60]:
a = np.vstack([[1,2,3],[[4,7],[5,8],[6,9]]]).T
np.random.shuffle(a)
print(a.T)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [56]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[1::5]

array([2, 7])

In [52]:
range?